version: '3.9'
services: 
  spark:
    image: saprk
    build: ./
    environment:
      - STORAGE_EMULATOR_HOST=http://storage:8080
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - ".:/test-files:rw"
    networks:
      - spark
  spark-worker:
    image: saprk
    build: ./
    environment:
      - STORAGE_EMULATOR_HOST=http://storage:8080
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ".:/test-files:rw"
    networks:
      - spark  
  storage:
    image: fsouza/fake-gcs-server
    ports:
      - 8081:8080
    volumes:
      - ./data:/data
    command: ["-scheme", "http", "-port", "8080","-external-url", "http://storage:8080"]
    networks:
      - spark
networks:
  spark:
    driver: bridge